### ISSUE TITLE
请教开发组我在安装时报错 

### ISSUE THREAD

**Issue by si7eka** [uniqueway/hwamei#1]
开发组成员  
     您好  
我按照咱们的文档进行安装和部署时
在运行 ./bin/hubot              后报错  
以下是从linux终端复制过来的报错内容，请您帮我看看哪里有问题谢谢。  

```bash
./bin/hubot                             
hwamei> [Wed Oct 24 2018 14:03:56 GMT+0800 (CST)] ERROR Unable to load /home/itom/hwamei/scripts/webhook: /home/itom/hwamei/scripts/webhook.js:124
    async function sendMessage(chatId, messageObject){
          ^^^^^^^^

SyntaxError: Unexpected token function
  at createScript (vm.js:56:10)
  at Object.runInThisContext (vm.js:97:10)
  at Module._compile (module.js:549:28)
  at Object.Module._extensions..js (module.js:586:10)
  at Module.load (/home/itom/hwamei/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at tryModuleLoad (module.js:453:12)
  at Function.Module._load (module.js:445:3)
  at Module.require (module.js:504:17)
  at require (internal/module.js:20:19)
  at Robot.loadFile (/home/itom/hwamei/node_modules/hubot/src/robot.coffee:355:9, <js>:224:20)
  at Robot.load (/home/itom/hwamei/node_modules/hubot/src/robot.coffee:377:9, <js>:247:30)
  at Shell.loadScripts (/home/itom/hwamei/node_modules/hubot/bin/hubot:93:5, <js>:97:13)
  at Shell.g (events.js:292:16)
  at emitNone (events.js:86:13)
  at Shell.emit (events.js:185:7)
  at /home/itom/hwamei/node_modules/hubot/src/adapters/shell.coffee:35:7, <js>:72:22
  at /home/itom/hwamei/node_modules/hubot/src/adapters/shell.coffee:101:9, <js>:163:18
  at FSReqWrap.cb [as oncomplete] (fs.js:259:19)
```

**Comment by tlikai** [comment]
你没有运行 npm install 吧？

**Comment by si7eka** [comment]
> 你没有运行 npm install 吧？

有运行的且没有报错
![image](https://user-images.githubusercontent.com/15117469/49623435-a5043980-fa08-11e8-81d9-6abb35a9a728.png)

**Comment by tlikai** [comment]
node版本？

**Comment by si7eka** [comment]
> node版本？

node -v    
v6.14.3

**Comment by tlikai** [comment]
> > node版本？
> 
> node -v
> v6.14.3

更新下node版本吧

**Comment by si7eka** [comment]
> > > node版本？
> > 
> > 
> > node -v
> > v6.14.3
 
> 更新下node版本吧



> > > node版本？
> > 
> > 
> > node -v
> > v6.14.3
> 
> 更新下node版本吧

升级到v11.22.0 之后执行./bin/hubot 正常了，万分谢谢
