### ISSUE TITLE
generateUUID函数找不到.

### ISSUE THREAD

**Issue by ser163** [uniqueway/hwamei#3]
hwamei> [Sat Jun 01 2019 01:53:57 GMT+0800 (China Standard Time)] ERROR ReferenceError: generateUUID is not defined
  at TextListener.robot.hear [as callback] (/opt/hwamei/scripts/webhook.js:26:19)
  at executeListener (/opt/hwamei/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/opt/hwamei/node_modules/hubot/src/middleware.coffee:44:37, <js>:34:16)
  at /opt/hwamei/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/opt/hwamei/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/opt/hwamei/node_modules/async/lib/async.js:268:15)
  at /opt/hwamei/node_modules/hubot/src/middleware.coffee:49:7, <js>:37:22
  at process._tickCallback (internal/process/next_tick.js:61:11)
应该是作者更新版本的过程中误删除了.

**Comment by ser163** [comment]
应该是我本地版本库更新的问题.误报

**Comment by ser163** [comment]
晕了.太晚了,精力有点不行,看错文件了.的确是个bug.我修复了.

**Comment by ser163** [comment]
handlers 也少了.一起补上了.

**Comment by tlikai** [comment]
确实是有问题，合并了，谢谢。

**Comment by ser163** [comment]
客气了,开源事业人人支持.
